### ISSUE TITLE
The prop value with an expression type of AssignmentExpression could not be resolved.

### ISSUE THREAD

**Issue by SimpleCookie** [evcohen/jsx-ast-utils#65]
Seems similar to [this](https://github.com/evcohen/jsx-ast-utils/issues/7).

`The prop value with an expression type of AssignmentExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of AssignmentExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extract [as JSXExpressionContainer] (/Users/simple/Documents/web-preorder/node_modules/jsx-ast-utils/lib/values/expressions/index.js:179:11)
    at getValue (/Users/simple/Documents/web-preorder/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/Users/simple/Documents/web-preorder/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/Users/simple/Documents/web-preorder/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /Users/simple/Documents/web-preorder/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:78:95
    at Array.some (<anonymous>)
    at JSXOpeningElement (/Users/simple/Documents/web-preorder/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:77:52)
    at listeners.(anonymous function).forEach.listener (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/linter.js:997:32)
    at Traverser._traverse (/Users/simple/Documents/web-preorder/node_modules/eslint/lib/util/traverser.js:132:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by SimpleCookie** [comment]
My apologies, seems like it was a problem in my code, causing the linter to blame other stuff.

**Comment by rheaditi** [comment]
> My apologies, seems like it was a problem in my code, causing the linter to blame other stuff.

@SimpleCookie can you share the code which was causing this issue and share the fix?

**Comment by SimpleCookie** [comment]
> > My apologies, seems like it was a problem in my code, causing the linter to blame other stuff.
> 
> @SimpleCookie can you share the code which was causing this issue and share the fix?

I don't remember which part of my code that was causing it. But if you are interested, I can see if I can help you out to solve your issue?
