### ISSUE TITLE
TypeError: Cannot read property 'expression' of undefined

### ISSUE THREAD

**Issue by pragmaticivan** [evcohen/jsx-ast-utils#69]
```
at extract (/path/node_modules/jsx-ast-utils/lib/values/expressions/index.js:170:20)
    at /path/node_modules/jsx-ast-utils/lib/values/expressions/ObjectExpression.js:38:32
    at Array.reduce (<anonymous>)
    at Object.extractValueFromObjectExpression [as ObjectExpression] (/path/node_modules/jsx-ast-utils/lib/values/expressions/ObjectExpression.js:36:27)
    at extract (/path/node_modules/jsx-ast-utils/lib/values/expressions/index.js:183:21)
    at /path/node_modules/jsx-ast-utils/lib/values/expressions/ObjectExpression.js:38:70
    at Array.reduce (<anonymous>)
    at Object.extractValueFromObjectExpression [as ObjectExpression] (/path/node_modules/jsx-ast-utils/lib/values/expressions/ObjectExpression.js:36:27)
    at Object.extract [as JSXExpressionContainer] (/path/node_modules/jsx-ast-utils/lib/values/expressions/index.js:183:21)
    at getValue (/path/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
```

**Comment by ljharb** [comment]
Can you elaborate on when this happens, on what code?

**Comment by pragmaticivan** [comment]
I will try to dig deeper later to figure out which component is causing that. For now I added a check on `.extract` function to verify if the value is not undefined fist and it started working again.

**Comment by pragmaticivan** [comment]
I was able to figure out which part of the code is breaking. Doesn't seen to make a lot of sense.


```
<Link
          className={s.sortable}
          to={{
            pathname,
            query: {
              ...query,
              sort: `${sortKey}-${dir === 'asc' && isSorting ? 'desc' : 'asc'}`,
            },
          }}
        >
          {children}
</Link>
```
I fixed it by extracting the object inside `to=` to a new variable and passing the variable instead. It fixed the problem.

**Comment by fender** [comment]
I had the same issue.

Before (errors):
```es6
<Link to={{
  pathname: '/sign-up',
  state: { ...get(this.props.location, 'state', {}) },
}} />
```

After (no errors):
```es6
const state = { ...get(this.props.location, 'state', {}) };
...
<Link to={{
  pathname: '/sign-up',
  state,
}} />
```

**Comment by ljharb** [comment]
A PR would be great.

**Comment by tlaney** [comment]
Can confirm that I had the same issue, also when attempting to spread an object in a ReactRouter Link component.

Before(errors):
```
<Link to={{ pathname: manageRoute, state: {...data}}>Manage</Link>
```

After(no errors):
```
const stateForLink = {...data};
...
<Link to={{ pathname: manageRoute, state: stateForLink}>Manage</Link>
```

**Comment by jessebeach** [comment]
Fix for realz in https://github.com/evcohen/jsx-ast-utils/pull/75
