### ISSUE TITLE
The prop value with an expression type of ArrayExpression could not be resolved

### ISSUE THREAD

**Issue by zaschrim** [evcohen/jsx-ast-utils#7]
Looks similar to https://github.com/evcohen/jsx-ast-utils/issues/3

Error: The prop value with an expression type of ArrayExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extractLiteral [as JSXExpressionContainer] (C:\ProjectDirectory\app\app.v4\node_modules\jsx-ast-utils\lib\values\expressions\index.js:182:11)
    at getLiteralValue (C:\ProjectDirectory\app\app.v4\node_modules\jsx-ast-utils\lib\values\index.js:65:35)
    at extractValue (C:\ProjectDirectory\app\app.v4\node_modules\jsx-ast-utils\lib\getPropValue.js:24:12)
    at getLiteralPropValue (C:\ProjectDirectory\app\app.v4\node_modules\jsx-ast-utils\lib\getPropValue.js:56:10)
    at EventEmitter.JSXOpeningElement (C:\ProjectDirectory\app\app.v4\node_modules\eslint-plugin-jsx-a11y\lib\rules\role-supports-aria-props.js:50:69)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (C:\ProjectDirectory\app\app.v4\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\ProjectDirectory\app\app.v4\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (C:\ProjectDirectory\app\app.v4\node_modules\eslint\lib\util\comment-event-generator.js:97:23)

**Comment by evcohen** [comment]
thanks for reporting!! will get a fix for you in by the EOD

**Comment by evcohen** [comment]
[v1.3.3](https://github.com/evcohen/jsx-ast-utils/releases/tag/1.3.3) published with fix!
