### ISSUE TITLE
Error: The prop value with an expression type of SpreadElement could not be resolved.

### ISSUE THREAD

**Issue by connorjburton** [evcohen/jsx-ast-utils#73]
I am getting the following error

```
Error: The prop value with an expression type of SpreadElement could not be resolved.
  Please file issue to get this fixed immediately.
    at extract (C:\G2\G2\node_modules\jsx-ast-utils\lib\values\expressions\index.js:179:11)
    at C:\G2\G2\node_modules\jsx-ast-utils\lib\values\expressions\ArrayExpression.js:22:32
    at Array.map (<anonymous>)
    at extractValueFromArrayExpression (C:\G2\G2\node_modules\jsx-ast-utils\lib\values\expressions\ArrayExpression.js:21:25)
    at Object.ArrayExpression (C:\G2\G2\node_modules\jsx-ast-utils\lib\values\expressions\index.js:143:46)
    at Object.extractLiteral [as JSXExpressionContainer] (C:\G2\G2\node_modules\jsx-ast-utils\lib\values\expressions\index.js:205:29)
    at getLiteralValue (C:\G2\G2\node_modules\jsx-ast-utils\lib\values\index.js:61:35)
    at extractValue (C:\G2\G2\node_modules\jsx-ast-utils\lib\getPropValue.js:24:12)
    at getLiteralPropValue (C:\G2\G2\node_modules\jsx-ast-utils\lib\getPropValue.js:56:10)
    at getTabIndex (C:\G2\G2\node_modules\eslint-plugin-jsx-a11y\lib\util\getTabIndex.js:17:59)
```

It seems to related to the following line

`tabIndex={[...this.props.tabIndex, intIndex]}`

**Comment by jessebeach** [comment]
AST Spread Nodes are driving me nuts :)

I'll get this fixed.

**Comment by jessebeach** [comment]
Fixed in https://github.com/evcohen/jsx-ast-utils/pull/76
